---
# tasks file for ansible-role-dcos
- name: set dcos template location
  set_fact:
    dcos_tpl: "build/{{environ}}-dcos.json"

- name: dcos template
  template: src=dcos.json.j2 dest={{dcos_tpl}}

- name: verify JSON
  command: python -mjson.tool {{dcos_tpl}}
  changed_when: false

- name: Upload template to s3
  s3:
    bucket: "{{ cfn_template_bucket }}"
    src: "{{ dcos_tpl }}"
    object: "{{ environ }}/{{ dcos_tpl }}"
    mode: put
    security_token: "{{ lookup('env','AWS_SESSION_TOKEN') }}"

- name: Create DCOS stack
  cloudformation:
    template_url: "{{ cfn_template_url }}"
    region: "{{ region }}"
    stack_name: "{{ environ }}-mgage-dcos"
    security_token: "{{ lookup('env','AWS_SESSION_TOKEN') }}"
    tags:
      "mGage:env": "{{ environ }}"
      "mGage:unit": "techops"
      "mGage:product": "mesos"
      "mGage:subproduct": "mesos-infrastructure"
      "mGage:owner": "sysadmins@mGage.com"
  register: dcos_stack

- debug: var=dcos_stack.stack_outputs
